### ISSUE TITLE
Cloned repo is not accessible from host machine

### ISSUE THREAD

**Issue by iamthechad** [kappataumu/vagrant-up-github-pages#1]
I don't know if there was an intent to link the cloned repository to `/srv/www`, but with the current configuration the repository is not accessible from the host machine.

**Comment by kappataumu** [comment]
Nice catch, thanks for the heads up! 

Went a bit overboard when cleaning up; there was a missing `cd /srv/www` right before cloning the repo which meant that everything was happening in `~/vagrant`. I'm now explicitly specifying absolute paths, which is nicer (and allows the host to see the files in the local `www` folder). I guess a symlink could work as well, but i don't like keeping stuff in `HOME`.

Should be fine now.
