### ISSUE TITLE
Needed to run Jekyll on host 0.0.0.0 instead of default 127.0.0.1

### ISSUE THREAD

**Issue by maxmelnick** [kappataumu/vagrant-up-github-pages#2]
Great work with this setup! Only thing I had trouble with was getting to http://localhost:4000 on the host (even when `curl localhost:4000` worked on the guest). I figured out that I had to update the jekyll run script to run on host 0.0.0.0 so that it would work. This happened for me both on OSX (El Capitan) and Windows 8 each running VirtualBox 5.

Here's my updated line 83 in `bootstrap.sh`

**Before:**

```
run="start-stop-daemon --start --chuid vagrant:vagrant --exec $wrapper -- serve --source $clonedir --destination /home/vagrant/_site --watch --force_polling >> $log 2>&1 &"
```

**After:**

```
run="start-stop-daemon --start --chuid vagrant:vagrant --exec $wrapper -- serve --host 0.0.0.0 --source $clonedir --destination /home/vagrant/_site --watch --force_polling >> $log 2>&1 &"
```

**Comment by kappataumu** [comment]
Hello! Yes, it used to be that Jekyll listened on `0.0.0.0`, but it was [changed](https://github.com/jekyll/jekyll/pull/3053). A workaround is to put the host in `_config.yml`, [like I've been doing](https://github.com/kappataumu/kappataumu.github.com/blob/master/_config.yml). It feels "cleaner".

I think that you bring up an important issue though, this caveat should either be documented or change the defaults as you propose. I lean towards the latter, less surprises is better.

**Comment by xcatliu** [comment]
I met the same issue, when developing sites on a VirtualBox system, host system CANNOT visit site that listened on 127.0.0.1 in the virtual machine. After I set host to 0.0.0.0 in `_config.yml`, problem solved.
